### ISSUE TITLE
QG checks (Release 23.04)

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-bpn-discovery#109]
## QG checks
Please keep this issue open until QG is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG is concluded!

Product Owner: @thomas-henn 
Dev SPOC: @tunacicek, @agg3fe 
Helm Chart Version: [0.1.18](https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/bpndiscovery-0.1.18)
App Version: [0.2.8](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.1.18/charts/bpndiscovery/Chart.yaml#L28)

Release Managemnet Reference Issue: https://github.com/eclipse-tractusx/sig-release/issues/503

### Check of Tractus-X Release Guidelines

- Currently implemented automatic checks can be found under your product on our [Release Guidelines Checks Board](https://eclipse-tractusx.github.io/sig-release/) 
- This QG Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release)

#### TRG 1 Documentation

- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` 
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate install instructions either `INSTALL.md` or in `README.md`
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
- [x] #111

#### TRG 2 Git

- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) leading product repository
- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format

#### TRG 3 Kubernetes

- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) persistent volume and persistent volume claim is used when needed

#### TRG 4 Container

- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02) base image is agreed  
- [x] #115
- [x] #112
- [x] #113

#### TRG 5 Helm

- [x] #114
- [x] #116
- [x] [TRG 5.03](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-03) proper version strategy 
- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04) CPU / MEM resource requests and limits and are properly set
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) Application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) Dependencies are present and properly configured in the Chart.yaml
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) Product has a single deployable helm chart that contains all components 
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability
 
#### TRG 6 Released Helm Chart

- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 

#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  
- [x] [TRG 7.03](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03) IP checks for project content 
- [x] #118
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation
- [x] [TRG 7.08](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-08) Legal notice for KIT documentation

**Comment by FaGru3n** [comment]
Hi all are these the proper information for the QG-Checks?

Product Owner: @bs-sili
Dev SPOC: @tunacicek
Helm Chart Version: [0.2.3](https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/bpndiscovery-0.2.3)
App Version: [0.2.8](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.2.3/charts/bpndiscovery/Chart.yaml#L28C1-L28C18)

**Comment by tunacicek** [comment]
> Hi all are these the proper information for the QG-Checks?
> 
> Product Owner: @bs-sili Dev SPOC: @tunacicek Helm Chart Version: [0.2.3](https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/bpndiscovery-0.2.3) App Version: [0.2.8](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.2.3/charts/bpndiscovery/Chart.yaml#L28C1-L28C18)

Hi @FaGru3n ,
no the correct one is: 
Product Owner: @thomas-henn 
Dev SPOC: @tunacicek, @agg3fe 
Helm Chart Version: [0.1.18](https://github.com/eclipse-tractusx/sldt-bpn-discovery/tree/bpndiscovery-0.1.18)
App Version: [0.2.8](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.2.3/charts/bpndiscovery/Chart.yaml#L28C1-L28C18)

**Comment by FaGru3n** [comment]
Hi all, 

finished the first check on QG process and pointed every finding into separate issue, main parts are Dash Licence Validation in your pom.xml, the point with non root container userid´s/groupid´s and some diagrams that could also in a more programalical way like mermaid/puml/ or even draw.io with a little description how to maintain theese files.

Some quickfixes i alreadey created as a little pr so thanks for cooperation and please recheck the found issues.

FYI @thomas-henn 

Thanks in advance.

**Comment by FaGru3n** [comment]
> Hi @FaGru3n, thank you for checking the TRGs. The open issues are fixed and merge. Only the issue #111 is still open. I added a comment on this issue. Could you check it again please :)

After a discussion within the office hour and the awareness of editable files through our products informed @tunacicek that for old diagram files that have to be editable.

Agreed that theese file will be presented in the upcomming release.
