### ISSUE TITLE
BPNDiscovery:TRG 1.04 editable static files

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-bpn-discovery#111]
Hi found some diagrams that are stored as `.png` and have to migrated to some drawing language from our TRG.
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4#description

examples:
https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.1.18/docs/media/AddBatchFlow.PNG
https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.1.18/docs/media/AddFlow.PNG

and if you want to use Draw.io you should also add a little description how to maintain theese diagrams. 
--> https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4#drawio-example

example: 
https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/bpndiscovery-0.1.18/docs/media/drawings/AblaufSaveEntry_BD.drawio

**Comment by FaGru3n** [comment]
Sorry what was the outcome of the disscussion, sorry to many information at the same time 😉

**Comment by tunacicek** [comment]
> Sorry what was the outcome of the disscussion, sorry to many information at the same time 😉

For existing diagrams we keep it as is. Because we have only the png files without the original file. For some diagrams we have the draw.io files which we updated to the repository. 
But for new diagrams in feature we will use PUML or mermaid.

**Comment by FaGru3n** [comment]
Sure but with a cleanup for outdated files would also a good option right now.
And your files could be also migrated to the new format, before consortia time will end.

**Comment by tunacicek** [comment]
Hi @FaGru3n,
fine for me :) 
Is it fine for you to do this in the current release (24.05)?

**Comment by FaGru3n** [comment]
Kay just want to keep the awareness high so would be fine for me, will check the current QG Check (24.03) and leave the issue open for the release (24.05) but then it is really important to have editable iteams and diagrams because of the maintainabilty for upcomming people or joiners...

**Comment by tunacicek** [comment]
> Kay just want to keep the awareness high so would be fine for me, will check the current QG Check (24.03) and leave the issue open for the release (24.05) but then it is really important to have editable iteams and diagrams because of the maintainabilty for upcomming people or joiners...

Thank you @FaGru3n  :) 
I added this issue to our sprint board.

**Comment by tunacicek** [comment]
Hi @FaGru3n, 
i created the following PR: 
https://github.com/eclipse-tractusx/sldt-bpn-discovery/pull/125
