### ISSUE TITLE
TRG 5.01 Helm chart requirements

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-bpn-discovery#114]
https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/b6d4765beaf5f020d394e2431f80ec0c3e44899e/charts/bpndiscovery/values.yaml#L88

default user name should be changed

**Comment by tunacicek** [comment]
Hi @FaGru3n, 

PR is created : https://github.com/eclipse-tractusx/sldt-bpn-discovery/pull/120
