### ISSUE TITLE
Use random passwords provided by bitnami PostgreSQL Chart on default `values.yaml`

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sldt-bpn-discovery#37]
## Description

The default `values.yaml` does contain hard coded [passwords for the PostgreSQL dependency](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/v0.2.4-M1/charts/bpndiscovery/values.yaml#L92) and another set of credentials in the [datasource config](https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/v0.2.4-M1/charts/bpndiscovery/values.yaml#L62) 

There was a [Thread on our tractusx-dev mailing list](https://www.eclipse.org/lists/tractusx-dev/msg00184.html) discussing how to best use the information provided by the Postgres Chart dependency itself. Take a look there and see if you can adopt the approach pointed out there.

related to #28

**Comment by agg3fe** [comment]
Thanks for pointing this. we will check this.

**Comment by tunacicek** [comment]
Done. Issue will be closed.
