### ISSUE TITLE
Add `helm upgrade` workflow

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sldt-bpn-discovery#38]
## Description

[TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) specifies the need of a GitHub workflow, that checks if a `helm upgrade` can be done from the latest released Chart to the current version of the Chart in this repository.

An example of how that can be done is included in the example workflow shown in [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09).

related to, but not blocking #28 

This workflow can also be added after the current QGate phase

**Comment by agg3fe** [comment]
Thanks for providing the information. we will work on it and contact you in case we need more information.
