### ISSUE TITLE
Clarification: Legal info for distribution (TRG 7.05)

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sldt-bpn-discovery#39]
## Description 

[TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) describes, that the legal info (at least `NOTICE.md`, `DEPENDENCIES` and `LICENSE`) have to be included in the distribution artifact. In this case the .jar, that is build for the service.

Could you please verify and point out, if these files are included? I could not find a matching build config, but I also do not have good insight in your build setup.

If this is missing, it is blocking #28 

## Additional info

This [build config](https://github.com/eclipse-tractusx/digital-product-pass/blob/main/consumer-backend/productpass/pom.xml#L189-L202) works for the digital-product-pass app, which is also maven based

**Comment by tunacicek** [comment]
@SebastianBezold : On building the image, we copy the required files into the jar file (META-INF). 
See also: https://github.com/eclipse-tractusx/sldt-bpn-discovery/blob/3e6b24bc815ee382df1e57c239e50968a3d5c100/backend/pom.xml#L211
