### ISSUE TITLE
How do I know the `key` under which I need to register

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/sldt-bpn-discovery#46]
As a data provider (not OEM), how do I know under which key I need to register my stuff? And what should be the value?

**Comment by bs-sili** [comment]
Hi @florianrusch-zf ,
if I understood your question correctly it is not about how to enter an exact type / key combination with the bpn to the bpn discovery. It is about to know in which bpn discovery to enter the data, right?
This can be done with Discovery Finder service. 
Here you can search for bpn discoveries for a certain type 
[Search request of Discovery Finder](https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/docs/6-concepts.md#post-apiv10administrationconnectorsdiscoverysearch) 
If you send an empty types array in the search request like this
{
 "types": []
}
all available bpn discoveries will be returned.

**Comment by florianrusch-zf** [comment]
Ahhh so if someone wants to register something which should be discoverable (e.g. a submodel for a gear box) he/she first needs to identify the type in the discovery finder before she/he can then register the regarding id in the bpn discovery?

**Comment by bs-sili** [comment]
Exactly, if you want to know which BPN Discovery manages which type, you can use the Discovery Finder. Also you will get the appropriate endpoint. The option of not entering a specific type in the search query means that all possible BPN Discoveries and their supported types are returned.
Of course, if you already know the endpoint for the needed BPN Discovery, then you do not need to use the Discovery Finder and go directly to the BPN Discovery.

**Comment by florianrusch-zf** [comment]
Thanks for the explanation! That helped already!

Another question would be, who is defining and providing/adding these types?

**Comment by bs-sili** [comment]
Hi,
the types can be set in the allowedTypes section. The person or the company which deploys the BPN Discovery can define what types are provided in this service.

**Comment by florianrusch-zf** [comment]
That means there is no "standard" set of types, that were aligned to be used within the catena-x ecosystem???

**Comment by bs-sili** [comment]
Hi, 
sorry, for my late response.
At the moment it is not standardized. It is more likely that adding a type will be done by asking the operator of the service to 
to permit the type.

**Comment by tunacicek** [comment]
The issue will be closed. For further questions, please create a new issue.
