### ISSUE TITLE
TRG 1.03 appropriate `CHANGELOG.md`

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-bpn-discovery#54]
Hi your Changelog describes that the currenct released version is `0.2.6`

just to clear my confusion, what is then with the newer release like [bpndiscovery-0.1.13](https://github.com/eclipse-tractusx/sldt-bpn-discovery/releases/tag/bpndiscovery-0.1.13)

**Comment by agg3fe** [comment]
@FaGru3n Changelog.md has been modified. 0.2.6 has been removed as the latest version is still 0.2.5.
https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/CHANGELOG.md

**Comment by FaGru3n** [comment]
> [@FaGru3n](https://github.com/FaGru3n) Changelog.md has been modified. 0.2.6 has been removed as the latest version is still 0.2.5.
https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/CHANGELOG.md

**Comment by FaGru3n** [comment]
also in tag there is a the told version

**Comment by FaGru3n** [comment]
this is finder repo not the https://github.com/eclipse-tractusx/sldt-bpn-discovery @agg3fe  could you please recheck the changelog.md
